module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests'],
  testMatch: ['**/?(*.)+(spec|test).ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/server.ts',
    '!src/types/**/*',
    '!src/constants/**/*',
    '!src/templates/**/*',
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@validators/(.*)$': '<rootDir>/src/validators/$1',
    '^@constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@helpers/(.*)$': '<rootDir>/src/helpers/$1',
    '^@repositories/(.*)$': '<rootDir>/src/repositories/$1',
    '^@exceptions/(.*)$': '<rootDir>/src/exceptions/$1',
    '^@events/(.*)$': '<rootDir>/src/events/$1',
    '^@jobs/(.*)$': '<rootDir>/src/jobs/$1',
    '^@cache/(.*)$': '<rootDir>/src/cache/$1',
    '^@logger/(.*)$': '<rootDir>/src/logger/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
};