export const EMAIL_TEMPLATES = {
  WELCOME: 'welcome',
  REGISTRATION_CONFIRMATION: 'registration-confirmation',
  PAYMENT_CONFIRMATION: 'payment-confirmation',
  RESET_PASSWORD: 'reset-password',
  CONTACT_REPLY: 'contact-reply',
  NEWSLETTER: 'newsletter',
  Y2C_WELCOME: 'y2c-welcome',
  Y2C_APPROVED: 'y2c-approved',
  EVENT_REGISTRATION: 'event-registration',
  INTERVIEW_SCHEDULED: 'interview-scheduled',
  APPLICATION_CONFIRMATION: 'application-confirmation',
  VERIFICATION_EMAIL: 'verification-email',
  PASSWORD_CHANGED: 'password-changed',
  ACCOUNT_SUSPENDED: 'account-suspended',
  ACCOUNT_REACTIVATED: 'account-reactivated',
  FORMATION_REMINDER: 'formation-reminder',
  FORMATION_CANCELLED: 'formation-cancelled',
  FORMATION_COMPLETED: 'formation-completed',
  SURVEY_INVITATION: 'survey-invitation',
  FEEDBACK_REQUEST: 'feedback-request',
  PROMOTIONAL: 'promotional',
  SYSTEM_NOTIFICATION: 'system-notification',
} as const;

export type EmailTemplate = typeof EMAIL_TEMPLATES[keyof typeof EMAIL_TEMPLATES];

export const EMAIL_SUBJECTS: Record<EmailTemplate, string> = {
  [EMAIL_TEMPLATES.WELCOME]: 'Bienvenue sur Youth Computing !',
  [EMAIL_TEMPLATES.REGISTRATION_CONFIRMATION]: 'Confirmation d\'inscription',
  [EMAIL_TEMPLATES.PAYMENT_CONFIRMATION]: 'Confirmation de paiement',
  [EMAIL_TEMPLATES.RESET_PASSWORD]: 'Réinitialisation de votre mot de passe',
  [EMAIL_TEMPLATES.CONTACT_REPLY]: 'Réponse à votre message',
  [EMAIL_TEMPLATES.NEWSLETTER]: 'Newsletter Youth Computing',
  [EMAIL_TEMPLATES.Y2C_WELCOME]: 'Bienvenue dans la communauté Y2C !',
  [EMAIL_TEMPLATES.Y2C_APPROVED]: 'Votre adhésion Y2C a été approuvée',
  [EMAIL_TEMPLATES.EVENT_REGISTRATION]: 'Confirmation d\'inscription à l\'événement',
  [EMAIL_TEMPLATES.INTERVIEW_SCHEDULED]: 'Entretien programmé',
  [EMAIL_TEMPLATES.APPLICATION_CONFIRMATION]: 'Confirmation de candidature',
  [EMAIL_TEMPLATES.VERIFICATION_EMAIL]: 'Vérifiez votre adresse email',
  [EMAIL_TEMPLATES.PASSWORD_CHANGED]: 'Votre mot de passe a été modifié',
  [EMAIL_TEMPLATES.ACCOUNT_SUSPENDED]: 'Votre compte a été suspendu',
  [EMAIL_TEMPLATES.ACCOUNT_REACTIVATED]: 'Votre compte a été réactivé',
  [EMAIL_TEMPLATES.FORMATION_REMINDER]: 'Rappel : Formation à venir',
  [EMAIL_TEMPLATES.FORMATION_CANCELLED]: 'Formation annulée',
  [EMAIL_TEMPLATES.FORMATION_COMPLETED]: 'Formation terminée',
  [EMAIL_TEMPLATES.SURVEY_INVITATION]: 'Invitation à participer à un sondage',
  [EMAIL_TEMPLATES.FEEDBACK_REQUEST]: 'Nous aimerions avoir votre avis',
  [EMAIL_TEMPLATES.PROMOTIONAL]: 'Offre spéciale Youth Computing',
  [EMAIL_TEMPLATES.SYSTEM_NOTIFICATION]: 'Notification système',
};