export const PERMISSIONS = {
  // User management
  MANAGE_USERS: 'manage_users',
  MANAGE_ROLES: 'manage_roles',
  
  // Content management
  MANAGE_ARTICLES: 'manage_articles',
  MANAGE_FORMATIONS: 'manage_formations',
  MANAGE_Y2C: 'manage_y2c',
  MANAGE_PROJECTS: 'manage_projects',
  MANAGE_EVENTS: 'manage_events',
  MANAGE_TEAM: 'manage_team',
  MANAGE_PARTNERS: 'manage_partners',
  MANAGE_RECRUITMENTS: 'manage_recruitments',
  
  // Dashboard
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_REPORTS: 'view_reports',
  EXPORT_DATA: 'export_data',
  
  // System
  MANAGE_SETTINGS: 'manage_settings',
  MANAGE_CONTACT: 'manage_contact',
  MANAGE_PAYMENTS: 'manage_payments',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const PERMISSION_GROUPS = {
  USER_MANAGEMENT: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ROLES,
  ],
  CONTENT_MANAGEMENT: [
    PERMISSIONS.MANAGE_ARTICLES,
    PERMISSIONS.MANAGE_FORMATIONS,
    PERMISSIONS.MANAGE_Y2C,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.MANAGE_TEAM,
    PERMISSIONS.MANAGE_PARTNERS,
    PERMISSIONS.MANAGE_RECRUITMENTS,
  ],
  DASHBOARD: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_DATA,
  ],
  SYSTEM: [
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.MANAGE_CONTACT,
    PERMISSIONS.MANAGE_PAYMENTS,
  ],
};

// Map des rôles vers les permissions
export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ARTICLES,
    PERMISSIONS.MANAGE_FORMATIONS,
    PERMISSIONS.MANAGE_Y2C,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.MANAGE_TEAM,
    PERMISSIONS.MANAGE_PARTNERS,
    PERMISSIONS.MANAGE_RECRUITMENTS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.MANAGE_CONTACT,
    PERMISSIONS.MANAGE_PAYMENTS,
  ],
  EDITOR: [
    PERMISSIONS.MANAGE_ARTICLES,
    PERMISSIONS.MANAGE_FORMATIONS,
    PERMISSIONS.MANAGE_Y2C,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  CONTRIBUTOR: [
    PERMISSIONS.MANAGE_ARTICLES,
    PERMISSIONS.MANAGE_PROJECTS,
  ],
  VIEWER: [],
};